### ISSUE TITLE
Unable to create emulator instance.

### ISSUE THREAD

**Issue by marcteys** [pebble/cloudpebble#161]
Hi, 
Each time I try to compile a project (PebbleJS or C ) on CloudPebble, the emulator cannot boot. I have this error : 'Emulator boot failed: Unable to create emulator instance.'

It was working before. I'm on Windows 8.2, I tried on Chrome and FF. 

Any ideas ?

**Comment by Katharine** [comment]
Should be resolved.

**Comment by marcteys** [comment]
Resolved. 
Pefect to finish my program on time, I receive my pebble tomorrow.
Thanks Katharine.

**Comment by dabdemon** [comment]
seems to be happening again... Any way to reopen?

**Comment by JNavas2** [comment]
Happening to me most of the day today.

**Comment by dombeef** [comment]
It only happened every 4 out of 5 times earlier today(like 6 hours ago) but is now every single attempt results in that error.

**Comment by orospakr** [comment]
Me too.  I'm going to guess that Chalk excitement has resulted in high load and thus a pool of containers/instances is exhausted? :(

**Comment by anavattva** [comment]
None of the cloud emulators are working at the moment.

**Comment by dlaufer** [comment]
Emulator isn't working...

**Comment by GatesWang** [comment]
Doesnt work for me either

**Comment by Sichroteph** [comment]
Same thing today, very frustrating

**Comment by bendellarocco** [comment]
Same issue currently

**Comment by bluabaleno** [comment]
same issue currently

**Comment by aflashyrhetoric** [comment]
Same here. Problems with the Basalt emulator. If it matters, I'm in NY.

**Comment by KrishnanSriram** [comment]
Completely stopped by this error. What's the fix? Anything I can do as a developer to fix it?

**Comment by flocsy** [comment]
again today :(

**Comment by LevoPinder** [comment]
And again for the past 4 hours

**Comment by joerozek** [comment]
Same here.

**Comment by billhsu** [comment]
again now.

**Comment by flocsy** [comment]
Anyone succeeded to set cloudpebble up locally via this: https://github.com/pebble/cloudpebble-composed ? Looks promising instead of cloudpebble.net

**Comment by Katharine** [comment]
I've made some configuration changes, added some more hardware, and [fixed a bug](https://github.com/pebble/cloudpebble/commit/26bc24ab1110c58af5ba32a527169dff3da57c07) that will hopefully improve the general reliability of emulators. Fingers crossed, then.

**Comment by gbetous** [comment]
Never could create emulator instance in CloudPebble, from Firefox in Linux.

**Comment by flocsy** [comment]
Funny, it actually worked today, but exactly when @gbetous posted is failed again...

**Comment by flocsy** [comment]
and again now...

**Comment by Katharine** [comment]
I think I've traced an actual fix for this, so this should be fixed for real fairly soon.

**Comment by joerozek** [comment]
I found a workaround that works for me.  If you click the play button and it fails, click the 'compilation' menu on the left. Then try clicking run build, or clicking the orange button for target platform (chalk, baslat, etc)

**Comment by flocsy** [comment]
@joerozek there seems to be 2 bugs. One is fixable as you wrote, but there seems to be another bug that looks like a problem related to "time", meaning there are times when the emulator won't start, and it doesn't matter how you try, until something gets fixed (I suppose someone restarts a service or the load on it drops)

**Comment by Katharine** [comment]
This should be fixed now.

**Comment by flocsy** [comment]
@Katharine, #1 still happens now: around every second time I need to refresh the browser in order for the emulator to start. When I finished checking my app on a platform I click on another platform in Compilation, and usually it fails, then I refresh and it works.

**Comment by Katharine** [comment]
Can you provide reproduction steps for it failing, as well as which browser you're using?

**Comment by flocsy** [comment]
0. I use Chrome 54 on Mac OSX 10.11.6
1. try project 373484 or import github.com/flocsy/pebble_zman
2. run build
3. start in Aplite
4. after it installed successfully dismiss the modal
5. start in Basalt
6. after it installed successfully dismiss the modal
7. start in Chalk
8. after it installed successfully dismiss the modal
9. start in Diorite
10. after it installed successfully dismiss the modal
11. start in Emery

previously (when I wrote my last comment) I was working on layout positions so I was jumping between A|B|D and C and E

To tell you the truth right now this doesn't happen, but when I started Emery it stopped at "Preparing to install app…" and it's stuck there for at least 10 minutes

**Comment by flocsy** [comment]
Ok another:

1. after refresh, tried to start it in Emery again, but still the same: emulator is black, and not finishing
2. I clicked NEXT to the modal to close it
3. I clicked on Chalk
4. it loaded the emulator for a second then it disappeared
5. clicking again on Chalk works

**Comment by flocsy** [comment]
we have the problem again. It looks like emery emulators have the problem, and it works in something like 10% of the retries, but fails 90%
